version: '3.4'

services:
  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_DB: "managerkit"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  manager_kit_server:
    container_name: manager_kit_server
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/managerkit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres