version: '3.4'

services:
  postgres:
    image: postgres:11.0
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example_pass
      POSTGRES_DB: example_app